services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_BRANCH: ${NEXT_PUBLIC_BRANCH}
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
