import type { TypographyProps as MuiTypographyProps } from "@mui/material/Typography";

export interface TypographyProps extends MuiTypographyProps {
  fontType?:
    | "regular-displayLG"
    | "regular-displayMD"
    | "regular-headingLG"
    | "regular-headingMD"
    | "regular-headingSM"
    | "regular-subheading"
    | "regular-paragraphLG"
    | "regular-paragraphMD"
    | "regular-paragraphSM"
    | "regular-captionLG"
    | "regular-captionMD"
    | "regular-linkMD"
    | "regular-linkSM"
    | "medium-displayLG"
    | "medium-displayMD"
    | "medium-headingLG"
    | "medium-headingMD"
    | "medium-headingSM"
    | "medium-subHeading"
    | "medium-paragraphLG"
    | "medium-paragraphMD"
    | "medium-paragraphSM"
    | "medium-captionLG"
    | "medium-captionMD"
    | "medium-linkMD"
    | "medium-linkSM"
    | "semibold-displayLG"
    | "semibold-displayMD"
    | "semibold-headingLG"
    | "semibold-headingMD"
    | "semibold-headingSM"
    | "semibold-subHeading"
    | "semibold-paragraphLG"
    | "semibold-paragraphMD"
    | "semibold-paragraphSM"
    | "semibold-captionLG"
    | "semibold-captionMD"
    | "semibold-linkMD"
    | "semibold-linkSM"
    | "bold-displayLG"
    | "bold-displayMD"
    | "bold-headingLG"
    | "bold-headingMD"
    | "bold-headingSM"
    | "bold-subHeading"
    | "bold-paragraphLG"
    | "bold-paragraphMD"
    | "bold-paragraphSM"
    | "bold-captionLG"
    | "bold-captionMD"
    | "bold-linkMD"
    | "bold-linkSM";
}
