import type { CustomVariantStyle } from "./types";

export const customVariantStyle: CustomVariantStyle = {
  regularDisplayLG: {
    fontSize: "var(--font-size-0)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-0)",
    letterSpacing: "-0.4px",
  },
  regularDisplayMD: {
    fontSize: "var(--font-size-1)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-1)",
  },
  regularHeadingLG: {
    fontSize: "var(--font-size-2)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-2)",
  },
  regularHeadingMD: {
    fontSize: "var(--font-size-3)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-3)",
  },
  regularHeadingSM: {
    fontSize: "var(--font-size-4)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-4)",
  },
  regularSubHeading: {
    fontSize: "var(--font-size-5)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-5)",
  },
  regularParagraphLG: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
  },
  regularParagraphMD: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
  },
  regularParagraphSM: {
    fontSize: "var(--font-size-8)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-8)",
  },
  regularCaptionLG: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
  },
  regularCaptionMD: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
  },
  regularLinkMD: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
    textDecorationLine: "underline",
  },
  regularLinkSM: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-regular)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
    textDecorationLine: "underline",
  },
  mediumDisplayLG: {
    fontSize: "var(--font-size-0)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-0)",
    letterSpacing: "-0.4px",
  },
  mediumDisplayMD: {
    fontSize: "var(--font-size-1)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-1)",
  },
  mediumHeadingLG: {
    fontSize: "var(--font-size-2)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-2)",
  },
  mediumHeadingMD: {
    fontSize: "var(--font-size-3)",
    fontWeight: "var(--font-weight-medium)",
    lineHeight: "var(--line-height-3)",
  },
  mediumHeadingSM: {
    fontSize: "var(--font-size-4)",
    fontWeight: "var(--font-weight-medium)",
    lineHeight: "var(--line-height-4)",
  },
  mediumSubHeading: {
    fontSize: "var(--font-size-5)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-5)",
  },
  mediumParagraphLG: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
  },
  mediumParagraphMD: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
  },
  mediumParagraphSM: {
    fontSize: "var(--font-size-8)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-8)",
  },
  mediumCaptionLG: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
  },
  mediumCaptionMD: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
  },
  mediumLinkMD: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
    textDecorationLine: "underline",
  },
  mediumLinkSM: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-medium)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
    textDecorationLine: "underline",
  },
  semiboldDisplayLG: {
    fontSize: "var(--font-size-0)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-0)",

    letterSpacing: " -0.4px",
  },
  semiboldDisplayMD: {
    fontSize: "var(--font-size-1)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-1)",
  },
  semiboldHeadingLG: {
    fontSize: "var(--font-size-2)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-2)",
  },
  semiboldHeadingMD: {
    fontSize: "var(--font-size-3)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-3)",
  },
  semiboldHeadingSM: {
    fontSize: "var(--font-size-4)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-4)",
  },
  semiboldSubHeading: {
    fontSize: "var(--font-size-5)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-5)",
  },
  semiboldParagraphLG: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
  },
  semiboldParagraphMD: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
  },
  semiboldParagraphSM: {
    fontSize: "var(--font-size-8)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-8)",
  },
  semiboldCaptionLG: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
  },
  semiboldCaptionMD: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
  },
  semiboldLinkMD: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
    textDecorationLine: "underline",
  },
  semiboldLinkSM: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-semibold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
    textDecorationLine: "underline",
  },
  boldDisplayLG: {
    fontSize: "var(--font-size-0)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-0)",
    letterSpacing: "-0.4px",
  },
  boldDisplayMD: {
    fontSize: "var(--font-size-1)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-1)",
    letterSpacing: "-0.32px",
  },
  boldHeadingLG: {
    fontSize: "var(--font-size-2)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-2)",
  },
  boldHeadingMD: {
    fontSize: "var(--font-size-3)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-3)",
  },
  boldHeadingSM: {
    fontSize: "var(--font-size-4)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-4)",
  },
  boldSubHeading: {
    fontSize: "var(--font-size-5)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-5)",
  },
  boldParagraphLG: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
  },
  boldParagraphMD: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
  },
  boldParagraphSM: {
    fontSize: "var(--font-size-8)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-8)",
  },
  boldCaptionLG: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
  },
  boldCaptionMD: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
  },
  boldLinkMD: {
    fontSize: "var(--font-size-6)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-6)",
    textDecorationLine: "underline",
  },
  boldLinkSM: {
    fontSize: "var(--font-size-7)",
    fontWeight: "var(--font-weight-bold)",
    fontStyle: "normal",
    lineHeight: "var(--line-height-7)",
    textDecorationLine: "underline",
  },
};
