name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          build_command: 'yarn build-storybook'
          install_command: 'yarn install --immutable --immutable-cache --check-cache'
          path: 'storybook-static'
