name: Deploy Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_STORYBOOK_URL: https://datawowio.github.io/nextjs-template
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          build_command: yarn build-storybook
          install_command: yarn install --frozen-lockfile
          path: storybook-static
