name: Deploy Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      NEXT_PUBLIC_BASE_STORYBOOK_URL: ${{ vars.NEXT_PUBLIC_BASE_STORYBOOK_URL }}

    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          build_command: NEXT_PUBLIC_BASE_STORYBOOK_URL=${{ vars.NEXT_PUBLIC_BASE_STORYBOOK_URL }} yarn build-storybook
          install_command: yarn install --frozen-lockfile
          path: storybook-static
